# Generated by Django 3.1.7 on 2021-03-30 18:32

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.constraints
import django_ltree_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', django_ltree_field.fields.LTreeField(db_index=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['path'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=django.contrib.postgres.indexes.GistIndex(fields=['path'], name='test_app_ca_path_e5731b_gist'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('path',), name='test_app_category_unique_path_deferred'),
        ),
    ]
