# Generated by Django 3.1.7 on 2021-04-01 20:06

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.constraints
import django_ltree_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortedNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', django_ltree_field.fields.LTreeField(db_index=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['path'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='sortednode',
            index=django.contrib.postgres.indexes.GistIndex(fields=['path'], name='test_app_so_path_9b408a_gist'),
        ),
        migrations.AddConstraint(
            model_name='sortednode',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('path',), name='test_app_sortednode_unique_path_deferred'),
        ),
    ]
